### ISSUE TITLE
.

### ISSUE THREAD

**Issue by tanshuai0219** [frederickszk/RL_final#1]

**Comment by frederickszk** [comment]
我刚刚找了一下还在~你留个邮箱给我吧，我晚点发过去
不过估计只能简单参考一下，这项目两个算法最后我都没有成功训练收敛😂

**Comment by s0219** [comment]
1016268283@qq.com 谢谢学长~

**Comment by s0219** [comment]
> 我刚刚找了一下还在~你留个邮箱给我吧，我晚点发过去 不过估计只能简单参考一下，这项目两个算法最后我都没有成功训练收敛😂

1016268283@qq.com 谢谢学长~

**Comment by davidwang200099** [comment]
请问学长如果没有训练收敛的话，得分如何呢？

**Comment by frederickszk** [comment]
@davidwang200099 得分的话在atari里边可能只有开始几次能跳到3分左右，平均得分一直都在1分多波动。推测可能是buffer不够大，我只用了25M而相关工作建议用90M左右。其它的原因我猜是可能代码实现的时候忽略了某些细节，我只是照着算法重写了一遍，可能有些细节操作也会影响结果。推荐试试其它的能成功运行的代码对比一下。
mujuco是直接整合的[ikostrikov's repo](https://github.com/ikostrikov/pytorch-a2c-ppo-acktr-gail)，网络输出的reward是有明显的减小，从-140多减到-30左右，但感觉也没有完全收敛，因为看运行效果，agent只有偶尔几步能往前走。

**Comment by davidwang200099** [comment]
那最后大作业得分怎么样啊😂

**Comment by frederickszk** [comment]
@davidwang200099 总评A-似乎是 细节分数没查到 估计给了个平均分吧😂
